
version: '3.2'

services:
  gitlab: 
    image: gitlab/gitlab-ce
    expose:
      - 22
      - 80
      - 443
    volumes:
      - type: volume
        source: ./gitlab/resources/server-configuration/config
        target: /etc/gitlab
      - type: volume
        source: ./gitlab/resources/server-configuration/logs
        target: /var/log/gitlab
      - type: volume
        source: ./gitlab/resources/server-configuration/data
        target: /var/opt/gitlab
    ports: 
      - 22:22
      - 80:80
      - 443:443
    restart: on-failure

  jenkins:
    build:
      context: ./jenkins
    links:
      - gitlab
    expose:
      - 8080
    ports: 
      - 5002:8080
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"
    restart: on-failure
    stdin_open: true
    tty: true

  docserver:
    build: ./docserver
    expose:
      - 3000
    ports: 
      - 3002:3000
    volumes: 
      - type: volume
        source: ./docserver/resources/web-server
        target: /var/doc-web-server
    command: node /var/doc-web-server/bin/www
    restart: on-failure
    stdin_open: true
    tty: true
