
version: '0.0.1'

services:
  ${gitlab-service}: 
    build: ./gitlab/
    expose:
      - "22"
      - "80"
      - "443"
    links:
      - ${jenkins-service}
      - ${docservice-service}
    volumes:
      - /Users/zhangyue/DockerServices/gitlab/config : /etc/gitlab
      - /Users/zhangyue/DockerServices/gitlab/logs : /var/log/gitlab
      - /Users/zhangyue/DockerServices/gitlab/data : /var/opt/gitlab
    ports: 
      - "22:22"
      - "80:80"
      - "443:443"

  ${jenkins-service}:
    build: ./jenkins/
    expose: 
      - "8080"
    links:
      - ${gitlab-service}
      - ${docservice-service}
    volumes:
      - ./jenknis/resources/ : /opt/
    ports: 
      - "5003:8080"
    command: services jenkins start && /bin/bash

  ${docservice-service}:
    build: ./doc-webserver/
    expose: 
      - "3000"
    links:
      - ${gitlab-service}
      - ${jenkins-service}
    volumes: 
      - ./doc-webserver/resources/web-server : /var/spa-web-server
    ports: 
      - "3000:3001"
    command: node -v && /bin/bash
