
version: '3'

services:
  gitlab: 
    image: gitlab/gitlab-ce
    expose:
      - 22
      - 80
      - 443
    volumes:
      - "./gitlab/resources/server-configuration/config:/etc/gitlab"
      - "./gitlab/resources/server-configuration/logs:/var/log/gitlab"
      - "./gitlab/resources/server-configuration/data:/var/opt/gitlab"
    ports: 
      - 22:22
      - 80:80
      - 443:443
    restart: on-failure

  jenkins:
    build:
      context: ./jenkins
    links:
      - gitlab
    expose:
      - 8080
    ports: 
      - 5002:8080
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"
    restart: on-failure
    stdin_open: true
    tty: true

  docserver:
    build: ./docserver
    expose:
      - 3000
    ports: 
      - 3002:3000
    volumes: 
      - "./docserver/resources/web-server:/var/doc-web-server"
    command: node /var/doc-web-server/bin/www
    restart: on-failure
    stdin_open: true
    tty: true
