
version: '0.0.1'

services:

  ${gitlab-service}: 
    build: ./gitlab/
    expose:
      - "${gitlab-port22-mapping}"
      - "${gitlab-port80-mapping}"
      - "${gitlab-port443-mapping}"
    links:
      - ${jenkins-service}
      - ${docservice-service}
    volumes:
      - ${gitlab-volumns-config} : /etc/gitlab
      - ${gitlab-volumns-logs} : /var/log/gitlab
      - ${gitlab-volumns-data} : /var/opt/gitlab
    ports: 
      - "${gitlab-port22-mapping}:22"
      - "${gitlab-port80-mapping}:80"
      - "${gitlab-port443-mapping}:443"

  ${jenkins-service}:
    build: ./jenkins/
    expose: 
      - "${jenkins-port8080-mapping}"
    links:
      - ${gitlab-service}
      - ${docservice-service}
    volumes:
      - ${jenkins-volumns} : /opt/
    ports: 
      - "${jenkins-port8080-mapping}:8080"
    command: services jenkins start && /bin/bash

  ${docservice-service}:
    build: ./doc-webserver/
    expose: 
      - "${docservice-port3000-mapping}"
    links:
      - ${gitlab-service}
      - ${jenkins-service}
    volumes: 
      - ${docservice-volumns} : /var/spa-web-server
    ports: 
      - "${docservice-port3000-mapping}:3000"
    command: node -v && /bin/bash
