
version: '3'

services:
  gitlab: 
    image: gitlab/gitlab-ce
    expose:
      - 22
      - 80
      - 443
    volumes:
      - "/Users/zhangyue/DockerServices/gitlab/config:/etc/gitlab"
      - "/Users/zhangyue/DockerServices/gitlab/logs:/var/log/gitlab"
      - "/Users/zhangyue/DockerServices/gitlab/data:/var/opt/gitlab"
    ports: 
      - 22:22
      - 80:80
      - 443:443

  jenkins:
    build:
      context: ./jenkins
    links:
      - gitlab
    ports: 
      - 5002:8080
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"
    tty: true

  docserver:
    build: ./docserver
    ports: 
      - 3002:3000
    tty: true
